### ISSUE TITLE
Err, what?

### ISSUE THREAD

**Issue by rugk** [capJavert/content-ref#1]
Sorry, but I did not get what this addon does. It looks nice and has something to do with refreshing a page that's all.

> Check URL for specific keywords that you define in options with one click of a button.

The addon looks until a keyword appears in a page and refreshes it? And how do I specify the keyword?

I think you should definitively improve the description of the addon.

So I just thought I'll try it out and when I go to GitHub e.g. and click on that nice new question button... nothing happens. I can not even see an error message.
So I have no idea how to use your addon.

**Comment by capJavert** [comment]
yeah maybe there are a bit clunky, i kinda made plugin for myself. You can
find plugin options when you go to add ons in firefox -> plugins -> there
you will see new plugin and when you click options there you will see form
where you can define keywords and urls you want to check. Plugin should be
out on mozzila site soon so when it is published i will make more
screenshots and guide there.

thanks for your interest in my plugin,
cheers

**Comment by rugk** [comment]
> Plugin should be out on mozzila site soon

It is already there. https://addons.mozilla.org/de/firefox/addon/content-referrer/

And thanks for the explanation. However if all settings and checks are in the settings I still do not get the purpose of the button. What does it do? (actually nothing visible as I discovered)

**Comment by capJavert** [comment]
it checks the page content with out you actually refreshing it, so if you
are waiting for some online content to be published like trailer on youtube
or comic on some site you can load keywords matching there names and then
check if those keywords are matched on those pages, if they are plugin
button will show red notifications, if not he will stay as it is, also in
version 1.0.1 (still waiting for firefox ack you can set time interval in
witch you want plugin to auto check URLs for defined keywords.

**Comment by rugk** [comment]
Okay, thanks for your explanation.

I think my question is answered.
